services:

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
    - ./certbot/webroot:/var/www/certbot
    - letsencrypt-certificates:/etc/letsencrypt
    entrypoint: /bin/sh -c
    command: >
      "certbot certonly --webroot
      --webroot-path=/var/www/certbot
      --email ${EDITOR_EMAIL}
      --agree-tos
      --no-eff-email
      -d ${EDITOR_DOMAIN}"

  certbot-nginx:
    image: nginx:1.27.4-alpine
    container_name: certbot-${EDITOR_DOMAIN}
    hostname: certbot-${EDITOR_DOMAIN}
    volumes:
    - ./certbot-nginx/default.conf.template:/etc/nginx/templates/default.conf.template:ro
    - ./certbot/webroot:/var/www/certbot:ro
    - letsencrypt-certificates:/etc/letsencrypt:ro
    ports:
    - "80:80"
    restart: unless-stopped

  editor-nginx:
    image: ${EDITOR_DOMAIN}:latest
    build:
      dockerfile: ./docker/Dockerfile
      context: ../
    container_name: editor-${EDITOR_DOMAIN}
    hostname: editor-${EDITOR_DOMAIN}
    volumes:
    - ./nginx/default.conf.template:/etc/nginx/templates/default.conf.template:ro
    - letsencrypt-certificates:/etc/letsencrypt:ro
    ports:
    - "443:443"
    environment:
    - EDITOR_DOMAIN=${EDITOR_DOMAIN}
    restart: unless-stopped

volumes:
  letsencrypt-certificates:
