services:

  editor-nginx:
    image: ${EDITOR_DOMAIN}:latest
    build:
      dockerfile: ./docker/editor-nginx/Dockerfile
      context: ../
    container_name: editor-nginx
    hostname: ${EDITOR_DOMAIN}
    volumes:
    - ./nginx/default.conf.template:/etc/nginx/templates/default.conf.template:ro
    - editor-certs:/etc/letsencrypt/live/${EDITOR_DOMAIN}:ro
    ports:
    - "443:443"
    networks:
    - editor.net
    environment:
    - EDITOR_DOMAIN=${EDITOR_DOMAIN}
    restart: unless-stopped

volumes:
  editor-certs:

networks:
  editor.net:
